import { MatchStatus, NormalizedLeague, NormalizedMatch, NormalizedPlayer, NormalizedTeam, SportType } from '../../../common/interfaces/sports.interface';

export const MOCK_LEAGUES: NormalizedLeague[] = [
  {
    id: 'league-4328',
    providerId: '4328',
    name: 'English Premier League',
    sport: SportType.SOCCER,
    country: 'England',
    badgeUrl: 'https://www.thesportsdb.com/images/media/league/badge/g9e11p1718818817.png',
    logoUrl: 'https://www.thesportsdb.com/images/media/league/logo/j6pwy71718818824.png',
    bannerUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    currentSeason: '2025-2026',
    description: 'The Premier League is the top tier of England\'s football pyramid, featuring 20 clubs.',
    standings: [
      { rank: 1, teamId: 'team-133604', teamName: 'Arsenal', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/uyhbfe1612464705.png', played: 28, won: 20, drawn: 5, lost: 3, goalsFor: 65, goalsAgainst: 22, goalDifference: 43, points: 65 },
      { rank: 2, teamId: 'team-133612', teamName: 'Manchester City', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png', played: 28, won: 19, drawn: 6, lost: 3, goalsFor: 68, goalsAgainst: 26, goalDifference: 42, points: 63 },
      { rank: 3, teamId: 'team-133602', teamName: 'Liverpool', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/c8hr2a1548888155.png', played: 28, won: 19, drawn: 5, lost: 4, goalsFor: 64, goalsAgainst: 28, goalDifference: 36, points: 62 },
      { rank: 4, teamId: 'team-133610', teamName: 'Chelsea', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png', played: 28, won: 15, drawn: 7, lost: 6, goalsFor: 52, goalsAgainst: 34, goalDifference: 18, points: 52 },
      { rank: 5, teamId: 'team-133613', teamName: 'Tottenham Hotspur', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/txsptx1583526569.png', played: 28, won: 15, drawn: 5, lost: 8, goalsFor: 55, goalsAgainst: 41, goalDifference: 14, points: 50 },
    ],
  },
  {
    id: 'league-4424',
    providerId: '4424',
    name: 'Indian Premier League',
    sport: SportType.CRICKET,
    country: 'India',
    badgeUrl: 'https://www.thesportsdb.com/images/media/league/badge/5k1krh1616428781.png',
    logoUrl: 'https://www.thesportsdb.com/images/media/league/logo/ipl-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80',
    currentSeason: '2026',
    description: 'The premier professional Twenty20 cricket league in India.',
    standings: [
      { rank: 1, teamId: 'team-cricket-1', teamName: 'Mumbai Indians', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/mumbai-indians.png', played: 14, won: 10, drawn: 0, lost: 4, goalsFor: 2450, goalsAgainst: 2200, goalDifference: 250, points: 20 },
      { rank: 2, teamId: 'team-cricket-2', teamName: 'Chennai Super Kings', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/csk.png', played: 14, won: 9, drawn: 0, lost: 5, goalsFor: 2380, goalsAgainst: 2210, goalDifference: 170, points: 18 },
      { rank: 3, teamId: 'team-cricket-3', teamName: 'Royal Challengers Bengaluru', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/rcb.png', played: 14, won: 8, drawn: 0, lost: 6, goalsFor: 2490, goalsAgainst: 2420, goalDifference: 70, points: 16 },
    ],
  },
  {
    id: 'league-4387',
    providerId: '4387',
    name: 'NBA',
    sport: SportType.BASKETBALL,
    country: 'USA',
    badgeUrl: 'https://www.thesportsdb.com/images/media/league/badge/f19j8j1534005085.png',
    logoUrl: 'https://www.thesportsdb.com/images/media/league/logo/nba.png',
    bannerUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
    currentSeason: '2025-2026',
    description: 'National Basketball Association featuring premier global basketball talent.',
    standings: [
      { rank: 1, teamId: 'team-bball-1', teamName: 'Boston Celtics', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/celtics.png', played: 70, won: 55, drawn: 0, lost: 15, goalsFor: 8400, goalsAgainst: 7600, goalDifference: 800, points: 110 },
      { rank: 2, teamId: 'team-bball-2', teamName: 'Golden State Warriors', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/warriors.png', played: 70, won: 48, drawn: 0, lost: 22, goalsFor: 8200, goalsAgainst: 7800, goalDifference: 400, points: 96 },
      { rank: 3, teamId: 'team-bball-3', teamName: 'Los Angeles Lakers', badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/lakers.png', played: 70, won: 45, drawn: 0, lost: 25, goalsFor: 8100, goalsAgainst: 7950, goalDifference: 150, points: 90 },
    ],
  },
  {
    id: 'league-4464',
    providerId: '4464',
    name: 'ATP Tour (Grand Slam)',
    sport: SportType.TENNIS,
    country: 'International',
    badgeUrl: 'https://www.thesportsdb.com/images/media/league/badge/atp-tour.png',
    logoUrl: 'https://www.thesportsdb.com/images/media/league/logo/atp.png',
    bannerUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
    currentSeason: '2026',
    description: 'Top-level worldwide tennis tournament circuit organized by the ATP.',
    standings: [],
  },
];

export const MOCK_TEAMS: NormalizedTeam[] = [
  {
    id: 'team-133604',
    providerId: '133604',
    name: 'Arsenal',
    shortName: 'ARS',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    country: 'England',
    stadium: 'Emirates Stadium',
    stadiumCapacity: 60704,
    badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/uyhbfe1612464705.png',
    logoUrl: 'https://www.thesportsdb.com/images/media/team/logo/arsenal-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80',
    formedYear: 1886,
    description: 'Arsenal Football Club is an English professional football club based in Islington, London, England.',
    website: 'https://www.arsenal.com',
    stats: { played: 28, wins: 20, draws: 5, losses: 3, points: 65, form: ['W', 'W', 'W', 'D', 'W'] },
  },
  {
    id: 'team-133612',
    providerId: '133612',
    name: 'Manchester City',
    shortName: 'MCI',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    country: 'England',
    stadium: 'Etihad Stadium',
    stadiumCapacity: 53400,
    badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png',
    formedYear: 1880,
    description: 'Manchester City Football Club is an English football club based in Manchester.',
    website: 'https://www.mancity.com',
    stats: { played: 28, wins: 19, draws: 6, losses: 3, points: 63, form: ['W', 'D', 'W', 'W', 'W'] },
  },
  {
    id: 'team-133602',
    providerId: '133602',
    name: 'Liverpool',
    shortName: 'LIV',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    country: 'England',
    stadium: 'Anfield',
    stadiumCapacity: 61276,
    badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/c8hr2a1548888155.png',
    formedYear: 1892,
    description: 'Liverpool Football Club is a professional football club in Liverpool, England.',
    website: 'https://www.liverpoolfc.com',
    stats: { played: 28, wins: 19, draws: 5, losses: 4, points: 62, form: ['W', 'W', 'L', 'W', 'D'] },
  },
  {
    id: 'team-133610',
    providerId: '133610',
    name: 'Chelsea',
    shortName: 'CHE',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    country: 'England',
    stadium: 'Stamford Bridge',
    stadiumCapacity: 40341,
    badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png',
    formedYear: 1905,
    description: 'Chelsea Football Club is an English professional football club based in Fulham, West London.',
    website: 'https://www.chelseafc.com',
    stats: { played: 28, wins: 15, draws: 7, losses: 6, points: 52, form: ['D', 'W', 'W', 'L', 'W'] },
  },
  {
    id: 'team-cricket-1',
    providerId: 'cricket-1',
    name: 'Mumbai Indians',
    shortName: 'MI',
    sport: SportType.CRICKET,
    leagueId: 'league-4424',
    leagueName: 'Indian Premier League',
    country: 'India',
    stadium: 'Wankhede Stadium',
    stadiumCapacity: 33108,
    badgeUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=200&q=80',
    formedYear: 2008,
    description: 'Mumbai Indians is a franchise cricket team based in Mumbai, Maharashtra, that competes in the IPL.',
    stats: { played: 14, wins: 10, draws: 0, losses: 4, points: 20, form: ['W', 'W', 'W', 'L', 'W'] },
  },
  {
    id: 'team-cricket-2',
    providerId: 'cricket-2',
    name: 'Chennai Super Kings',
    shortName: 'CSK',
    sport: SportType.CRICKET,
    leagueId: 'league-4424',
    leagueName: 'Indian Premier League',
    country: 'India',
    stadium: 'M. A. Chidambaram Stadium',
    stadiumCapacity: 38200,
    badgeUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=200&q=80',
    formedYear: 2008,
    description: 'Chennai Super Kings is a franchise cricket team based in Chennai, Tamil Nadu.',
    stats: { played: 14, wins: 9, draws: 0, losses: 5, points: 18, form: ['L', 'W', 'W', 'W', 'L'] },
  },
  {
    id: 'team-bball-1',
    providerId: 'bball-1',
    name: 'Boston Celtics',
    shortName: 'BOS',
    sport: SportType.BASKETBALL,
    leagueId: 'league-4387',
    leagueName: 'NBA',
    country: 'USA',
    stadium: 'TD Garden',
    stadiumCapacity: 19156,
    badgeUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=200&q=80',
    formedYear: 1946,
    description: 'The Boston Celtics are an American professional basketball team based in Boston.',
    stats: { played: 70, wins: 55, draws: 0, losses: 15, points: 110, form: ['W', 'W', 'W', 'W', 'W'] },
  },
  {
    id: 'team-bball-2',
    providerId: 'bball-2',
    name: 'Golden State Warriors',
    shortName: 'GSW',
    sport: SportType.BASKETBALL,
    leagueId: 'league-4387',
    leagueName: 'NBA',
    country: 'USA',
    stadium: 'Chase Center',
    stadiumCapacity: 18064,
    badgeUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=200&q=80',
    formedYear: 1946,
    description: 'The Golden State Warriors are an American professional basketball team based in San Francisco.',
    stats: { played: 70, wins: 48, draws: 0, losses: 22, points: 96, form: ['W', 'L', 'W', 'W', 'L'] },
  },
];

export const MOCK_PLAYERS: NormalizedPlayer[] = [
  {
    id: 'player-bukayo-saka',
    providerId: '34161397',
    teamId: 'team-133604',
    teamName: 'Arsenal',
    name: 'Bukayo Saka',
    sport: SportType.SOCCER,
    nationality: 'England',
    position: 'Right Winger',
    dateOfBirth: '2001-09-05',
    height: '1.78 m',
    weight: '72 kg',
    jerseyNumber: '7',
    thumbUrl: 'https://www.thesportsdb.com/images/media/player/thumb/g3f8f11612465103.jpg',
    cutoutUrl: 'https://www.thesportsdb.com/images/media/player/cutout/0b0z6n1612465108.png',
    description: 'Bukayo Ayoyinka T. M. Saka is an English professional footballer who plays as a right winger for Arsenal and England national team.',
    stats: { goals: 14, assists: 11, shotsOnTarget: 38, keyPasses: 62, matchesPlayed: 27 },
  },
  {
    id: 'player-erling-haaland',
    providerId: '34161400',
    teamId: 'team-133612',
    teamName: 'Manchester City',
    name: 'Erling Haaland',
    sport: SportType.SOCCER,
    nationality: 'Norway',
    position: 'Striker',
    dateOfBirth: '2000-07-21',
    height: '1.94 m',
    weight: '88 kg',
    jerseyNumber: '9',
    thumbUrl: 'https://www.thesportsdb.com/images/media/player/thumb/haaland.jpg',
    description: 'Erling Braut Haaland is a Norwegian professional footballer who plays as a striker for Manchester City and Norway national team.',
    stats: { goals: 24, assists: 6, shotsOnTarget: 52, keyPasses: 21, matchesPlayed: 26 },
  },
  {
    id: 'player-rohit-sharma',
    providerId: 'cricket-p1',
    teamId: 'team-cricket-1',
    teamName: 'Mumbai Indians',
    name: 'Rohit Sharma',
    sport: SportType.CRICKET,
    nationality: 'India',
    position: 'Opening Batsman',
    dateOfBirth: '1987-04-30',
    height: '1.75 m',
    jerseyNumber: '45',
    thumbUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=400&q=80',
    description: 'Rohit Gurunath Sharma is an Indian international cricketer and legendary opening batsman.',
    stats: { runs: 580, strikeRate: 154.2, centuries: 1, fifties: 4, matchesPlayed: 14 },
  },
  {
    id: 'player-stephen-curry',
    providerId: 'bball-p1',
    teamId: 'team-bball-2',
    teamName: 'Golden State Warriors',
    name: 'Stephen Curry',
    sport: SportType.BASKETBALL,
    nationality: 'USA',
    position: 'Point Guard',
    dateOfBirth: '1988-03-14',
    height: '1.88 m',
    weight: '84 kg',
    jerseyNumber: '30',
    thumbUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=400&q=80',
    description: 'Wardell Stephen Curry II is an American professional basketball player and greatest shooter in NBA history.',
    stats: { ppg: 27.8, apg: 5.6, rpg: 4.8, threePtPercentage: 42.4, matchesPlayed: 65 },
  },
  {
    id: 'player-carlos-alcaraz',
    providerId: 'tennis-p1',
    name: 'Carlos Alcaraz',
    sport: SportType.TENNIS,
    nationality: 'Spain',
    position: 'Singles Player',
    dateOfBirth: '2003-05-05',
    height: '1.83 m',
    thumbUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=400&q=80',
    description: 'Carlos Alcaraz Garfia is a Spanish professional tennis player and multi-Grand Slam champion.',
    stats: { grandSlams: 4, rank: 2, winRate: '82%', titles2026: 3 },
  },
];

export const MOCK_MATCHES: NormalizedMatch[] = [
  {
    id: 'match-live-101',
    providerId: 'live-101',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    season: '2025-2026',
    round: 'Matchday 29',
    homeTeam: {
      id: 'team-133604',
      name: 'Arsenal',
      badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/uyhbfe1612464705.png',
      score: 2,
    },
    awayTeam: {
      id: 'team-133610',
      name: 'Chelsea',
      badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png',
      score: 1,
    },
    startTime: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    status: MatchStatus.LIVE,
    minute: '67\'',
    venue: 'Emirates Stadium, London',
    referee: 'Michael Oliver',
    spectators: 60214,
    events: [
      { id: 'ev-1', minute: 18, type: 'goal', team: 'home', player: 'Bukayo Saka', assist: 'Martin Ødegaard' },
      { id: 'ev-2', minute: 42, type: 'goal', team: 'away', player: 'Cole Palmer', assist: 'Enzo Fernández' },
      { id: 'ev-3', minute: 58, type: 'goal', team: 'home', player: 'Kai Havertz', assist: 'Declan Rice' },
      { id: 'ev-4', minute: 63, type: 'yellow_card', team: 'away', player: 'Marc Cucurella' },
    ],
    stats: {
      possession: { home: 58, away: 42 },
      shotsOnTarget: { home: 7, away: 3 },
      totalShots: { home: 15, away: 8 },
      fouls: { home: 9, away: 12 },
      corners: { home: 6, away: 3 },
    },
    aiSummary: 'Arsenal maintain intense pressing in the second half. Kai Havertz restored the Gunners lead in the 58th minute following a crisp passing sequence initiated by Declan Rice.',
    lastSyncedAt: new Date().toISOString(),
    freshness: 'near-real-time',
  },
  {
    id: 'match-live-102',
    providerId: 'live-102',
    sport: SportType.CRICKET,
    leagueId: 'league-4424',
    leagueName: 'Indian Premier League',
    season: '2026',
    round: 'League Match 32',
    homeTeam: {
      id: 'team-cricket-1',
      name: 'Mumbai Indians',
      badgeUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=200&q=80',
      score: '178/4',
      subScores: ['18.2 Ov', 'CRR: 9.71'],
    },
    awayTeam: {
      id: 'team-cricket-2',
      name: 'Chennai Super Kings',
      badgeUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=200&q=80',
      score: '174/6',
      subScores: ['20.0 Ov', 'Target: 175'],
    },
    startTime: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    status: MatchStatus.LIVE,
    minute: '18.2 Ov',
    venue: 'Wankhede Stadium, Mumbai',
    referee: 'Nitin Menon',
    events: [
      { id: 'ev-c1', minute: 8, type: 'boundary', team: 'home', player: 'Rohit Sharma', detail: 'Six over long-on' },
      { id: 'ev-c2', minute: 14, type: 'wicket', team: 'home', player: 'Suryakumar Yadav', detail: 'c Dhoni b Jadeja' },
    ],
    aiSummary: 'Mumbai Indians require 2 runs from 10 balls with 6 wickets in hand. Rohit Sharma set the foundation with a blistering 64 off 36 deliveries.',
    lastSyncedAt: new Date().toISOString(),
    freshness: 'near-real-time',
  },
  {
    id: 'match-upcoming-201',
    providerId: 'up-201',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    season: '2025-2026',
    round: 'Matchday 30',
    homeTeam: {
      id: 'team-133612',
      name: 'Manchester City',
      badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png',
      score: undefined,
    },
    awayTeam: {
      id: 'team-133602',
      name: 'Liverpool',
      badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/c8hr2a1548888155.png',
      score: undefined,
    },
    startTime: new Date(Date.now() + 28 * 60 * 60 * 1000).toISOString(),
    status: MatchStatus.SCHEDULED,
    venue: 'Etihad Stadium, Manchester',
    referee: 'Anthony Taylor',
    lastSyncedAt: new Date().toISOString(),
    freshness: 'cached',
  },
  {
    id: 'match-upcoming-202',
    providerId: 'up-202',
    sport: SportType.BASKETBALL,
    leagueId: 'league-4387',
    leagueName: 'NBA',
    season: '2025-2026',
    round: 'Regular Season',
    homeTeam: {
      id: 'team-bball-1',
      name: 'Boston Celtics',
      badgeUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=200&q=80',
    },
    awayTeam: {
      id: 'team-bball-2',
      name: 'Golden State Warriors',
      badgeUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=200&q=80',
    },
    startTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    status: MatchStatus.SCHEDULED,
    venue: 'TD Garden, Boston',
    lastSyncedAt: new Date().toISOString(),
    freshness: 'cached',
  },
  {
    id: 'match-past-301',
    providerId: 'past-301',
    sport: SportType.SOCCER,
    leagueId: 'league-4328',
    leagueName: 'English Premier League',
    season: '2025-2026',
    round: 'Matchday 28',
    homeTeam: {
      id: 'team-133604',
      name: 'Arsenal',
      badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/uyhbfe1612464705.png',
      score: 3,
    },
    awayTeam: {
      id: 'team-133612',
      name: 'Manchester City',
      badgeUrl: 'https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png',
      score: 1,
    },
    startTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: MatchStatus.FINISHED,
    venue: 'Emirates Stadium, London',
    spectators: 60320,
    events: [
      { id: 'ev-p1', minute: 14, type: 'goal', team: 'home', player: 'Bukayo Saka' },
      { id: 'ev-p2', minute: 38, type: 'goal', team: 'home', player: 'Gabriel Martinelli' },
      { id: 'ev-p3', minute: 61, type: 'goal', team: 'away', player: 'Erling Haaland' },
      { id: 'ev-p4', minute: 88, type: 'goal', team: 'home', player: 'Declan Rice' },
    ],
    stats: {
      possession: { home: 51, away: 49 },
      shotsOnTarget: { home: 8, away: 4 },
      totalShots: { home: 16, away: 11 },
      fouls: { home: 11, away: 10 },
      corners: { home: 7, away: 5 },
    },
    aiSummary: 'A tactical masterclass by Arsenal who neutralised Manchester City midfield buildup and capitalized on fast transitions to secure a crucial 3-1 victory.',
    lastSyncedAt: new Date().toISOString(),
    freshness: 'cached',
  },
  {
    id: 'match-past-302',
    providerId: 'past-302',
    sport: SportType.TENNIS,
    leagueId: 'league-4464',
    leagueName: 'ATP Tour (Grand Slam)',
    season: '2026',
    round: 'Final',
    homeTeam: {
      id: 'tennis-t1',
      name: 'Carlos Alcaraz',
      badgeUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=200&q=80',
      score: '3',
      subScores: ['6-4', '3-6', '7-6', '6-3'],
    },
    awayTeam: {
      id: 'tennis-t2',
      name: 'Jannik Sinner',
      badgeUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=200&q=80',
      score: '1',
      subScores: ['4-6', '6-3', '6-7', '3-6'],
    },
    startTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: MatchStatus.FINISHED,
    venue: 'Centre Court',
    aiSummary: 'Carlos Alcaraz claimed the title after a grueling 4-set thriller with relentless baseline depth and tactical drop shots.',
    lastSyncedAt: new Date().toISOString(),
    freshness: 'cached',
  },
];
